import {
  PackageItem,
  PromotionItem,
  BannerItem,
  LeadItem,
  ApplicationItem,
  EquipmentItem,
  ArticleItem,
  FAQItem,
  AdminUser,
  StoreSettings,
} from '../types';

export const INITIAL_SETTINGS: StoreSettings = {
  store_name: 'บริษัท โฮมไฟเบอร์เนต999 จำกัด',
  store_tagline: 'รับติดเน็ตบ้านสมัคร ออนไลน์ได้ทั่วประเทศ รวดเร็ว ครบวงจร',
  phone_primary: '093-551-5442',
  phone_secondary: '093-551-5442',
  line_id: '@aisfibrefanclub',
  line_url: 'https://line.me/ti/p/@aisfibrefanclub',
  facebook_url: 'https://facebook.com/aisfibrenet999',
  youtube_video_url: 'https://youtu.be/EfgbNbszqbM?si=vIjxgPV3jDkdaIz8',
  working_hours: 'เปิดให้บริการ ทุกวัน 08.00 - 17.00 น.',
  address: 'บริษัท โฮมไฟเบอร์เนต999 จำกัด 512 หมู่ 1 ถนนรักสงบ ตำบลวิศิษฐ์ อำเภอเมือง จังหวัดบึงกาฬ 38000',
  email: 'contact@aisfibrenet999.com',
  dealer_code: 'DLR-999-NET',
  auto_assign_leads: true,
};

export const INITIAL_ADMIN_USERS: AdminUser[] = [
  {
    id: 'user-admin-1',
    name: 'กิตติพงษ์ ผู้จัดการระบบ (Admin)',
    email: 'admin@aisfibre999.com',
    role: 'ADMIN',
    avatar: 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?w=150&auto=format&fit=crop&q=80',
    phone: '081-234-5678',
    active: true,
  },
  {
    id: 'user-staff-1',
    name: 'สมหญิง ใจดี (ฝ่ายประสานงานติดตั้ง)',
    email: 'staff@aisfibre999.com',
    role: 'STAFF',
    avatar: 'https://images.unsplash.com/photo-1580489944761-15a19d654956?w=150&auto=format&fit=crop&q=80',
    phone: '089-876-5432',
    active: true,
  },
  {
    id: 'user-staff-2',
    name: 'ธีรวัฒน์ ช่างเทคนิคอาวุโส',
    email: 'tech@aisfibre999.com',
    role: 'STAFF',
    avatar: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=150&auto=format&fit=crop&q=80',
    phone: '086-555-4321',
    active: true,
  },
];

export const INITIAL_PACKAGES: PackageItem[] = [
  {
    id: 'pkg-bb24-1000',
    name: 'Broadband 24 (1 Gbps / 500 Mbps)',
    slug: 'broadband-24-1000-500',
    price: 499,
    originalPrice: 699,
    download_speed: 1000,
    upload_speed: 500,
    contract_month: 24,
    installation_fee: 0,
    description: 'แพ็กเกจเน็ตบ้านสุดคุ้มยอดนิยมอันดับ 1 เน็ตแรงระดับ Gigabit 1Gbps ดาวน์โหลดเร็วเต็มสปีด ฟรีเราเตอร์ WiFi 6',
    features: [
      'ความเร็ว 1,000 Mbps / 500 Mbps (1 Gbps)',
      'ฟรี! เราเตอร์อัจฉริยะ WiFi 6 Router สปีดแรงทะลุผนัง',
      'ฟรี! ค่าแรกเข้าและค่าบริการติดตั้งและเดินสาย 4,800 บาท',
      'รองรับการเชื่อมต่ออุปกรณ์มากกว่า 30 เครื่องพร้อมกัน',
      'สามารถปรับสปีดดาวน์โหลด/อัปโหลดได้ด้วย Speed Toggle',
      'บริการดูแลโดยทีมวิศวกรผู้เชี่ยวชาญตลอด 24 ชั่วโมง',
    ],
    equipment: ['Smart WiFi 6 Router AX3000 (1 ตัว)', 'Optical Network Terminal (ONT)'],
    category: 'BROADBAND24',
    badge: '🔥 ยอดนิยมอันดับ 1',
    image: 'https://images.unsplash.com/photo-1544716278-ca5e3f4abd8c?w=600&auto=format&fit=crop&q=80',
    active: true,
    recommendedFor: 'บ้านทั่วไป ทาวน์โฮม คอนโด สำหรับคนชอบดูวิดีโอ 4K และดาวน์โหลดไฟล์รวดเร็ว',
    tvIncluded: false,
  },
  {
    id: 'pkg-bb24-500',
    name: 'Broadband 24 (500 / 500 Mbps)',
    slug: 'broadband-24-500-500',
    price: 399,
    originalPrice: 599,
    download_speed: 500,
    upload_speed: 500,
    contract_month: 24,
    installation_fee: 0,
    description: 'เน็ตบ้านสปีดสมดุล ดาวน์โหลดและอัปโหลดเร็วเท่ากัน 500/500 Mbps เหมาะสำหรับการทำงาน WFH และเรียนออนไลน์',
    features: [
      'ความเร็วสมดุล 500 Mbps / 500 Mbps',
      'ฟรี! ยืมเราเตอร์ Wi-Fi 6 ประสิทธิภาพสูงตลอดการใช้งาน',
      'ฟรี! ค่าติดตั้งและค่าเดินสาย มูลค่า 4,800 บาท',
      'ประชุมออนไลน์ Zoom/Teams และส่งไฟล์ใหญ่ไม่สะดุด',
      'สปีดเสถียร ปิงต่ำ ปลอดภัยด้วยระบบ AIS Secure Net',
    ],
    equipment: ['WiFi 6 Gigabit Router (1 ตัว)', 'ONT Unit'],
    category: 'BROADBAND24',
    badge: '⚡ คุ้มค่า WFH',
    image: 'https://images.unsplash.com/photo-1516321318423-f06f85e504b3?w=600&auto=format&fit=crop&q=80',
    active: true,
    recommendedFor: 'ครอบครัวขนาด 2-4 คน ใช้งาน Work From Home และเรียนออนไลน์',
    tvIncluded: false,
  },
  {
    id: 'pkg-net-lite-gang',
    name: 'Net Lite Gang (500 / 500 Mbps) + PLAYBOX',
    slug: 'net-lite-gang-500',
    price: 599,
    originalPrice: 799,
    download_speed: 500,
    upload_speed: 500,
    contract_month: 24,
    installation_fee: 0,
    description: 'รวมเน็ตบ้านเร็ว 500 Mbps พร้อมกล่อง AIS PLAYBOX และสิทธิ์รับชม VIU Premium ฟรีไม่อั้น',
    features: [
      'ความเร็ว 500 Mbps / 500 Mbps',
      'ฟรี! กล่อง AIS PLAYBOX 4K พร้อมรีโมทสั่งงานด้วยเสียง',
      'ฟรี! สิทธิ์รับชม VIU Premium นาน 24 เดือน (ซีรีส์เกาหลี/วาไรตี้)',
      'ฟรี! เราเตอร์ Wi-Fi 6 ประสิทธิภาพสูง',
      'ฟรี! ค่าแรกเข้าและค่าติดตั้ง 4,800 บาท',
    ],
    equipment: ['Smart WiFi 6 Router', 'AIS PLAYBOX 4K Gen 3', 'Optical Network Terminal'],
    category: 'ENTERTAINMENT',
    badge: '🎬 เน็ต + ทีวี สุดคุ้ม',
    image: 'https://images.unsplash.com/photo-1593784991095-a205069470b6?w=600&auto=format&fit=crop&q=80',
    active: true,
    recommendedFor: 'ครอบครัวที่ชอบดูซีรีส์ ภาพยนตร์ และรายการวาไรตี้ผ่านทีวี',
    tvIncluded: true,
  },
  {
    id: 'pkg-net-standard-gang',
    name: 'Net Standard Gang (1 Gbps / 500 Mbps) + Max / HBO',
    slug: 'net-standard-gang-1000',
    price: 799,
    originalPrice: 999,
    download_speed: 1000,
    upload_speed: 500,
    contract_month: 24,
    installation_fee: 0,
    description: 'เน็ตบ้าน 1Gbps ความบันเทิงระดับโลก พร้อมกล่อง AIS PLAYBOX และสิทธิ์ชม Max (HBO) + VIU Premium',
    features: [
      'ความเร็วระดับกิกะบิต 1,000 Mbps / 500 Mbps',
      'ฟรี! กล่อง AIS PLAYBOX 4K HDR',
      'ฟรี! สิทธิ์รับชม Max (Warner Bros / HBO Originals / Harry Potter / DC)',
      'ฟรี! สิทธิ์ชม VIU Premium 24 เดือน',
      'ฟรี! เราเตอร์ Wi-Fi 6 ประสิทธิภาพสูง',
    ],
    equipment: ['WiFi 6 Router AX3000', 'AIS PLAYBOX 4K', 'ONT'],
    category: 'ENTERTAINMENT',
    badge: '🌟 รวม Max & HBO',
    image: 'https://images.unsplash.com/photo-1522869635100-9f4c5e86aa37?w=600&auto=format&fit=crop&q=80',
    active: true,
    recommendedFor: 'คอภาพยนตร์ฟอร์มยักษ์ ซีรีส์ HBO และผู้ที่ต้องการเน็ตสปีด 1Gbps',
    tvIncluded: true,
  },
  {
    id: 'pkg-net-smart-gang',
    name: 'Net Smart Gang (1 Gbps / 500 Mbps) + Mesh x2 + SIM 5G',
    slug: 'net-smart-gang-mesh-sim',
    price: 799,
    originalPrice: 999,
    download_speed: 1000,
    upload_speed: 500,
    contract_month: 24,
    installation_fee: 0,
    description: 'พิเศษเฉพาะลูกค้า AIS รายเดือน! เน็ต 1Gbps + Mesh WiFi 2 ตัวครอบคลุมบ้าน + กล่อง PLAYBOX + ซิมเน็ต 5G 10GB',
    features: [
      'ความเร็ว 1,000 / 500 Mbps แรงเต็มพิกัด',
      'ฟรี! เราเตอร์ Mesh WiFi 6 จำนวน 2 ตัว สัญญาณครอบคลุม 2 ชั้น',
      'ฟรี! ซิมการ์ดเน็ต AIS 5G ความเร็วสูงสุด 10GB/เดือน',
      'ฟรี! กล่อง AIS PLAYBOX + แพ็กเกจความบันเทิง',
      'ฟรี! ค่าติดตั้งและเดินสายภายนอก 4,800 บาท',
    ],
    equipment: ['Mesh WiFi 6 Router (2 ตัว)', 'AIS PLAYBOX 4K', 'AIS 5G SIM Card 10GB'],
    category: 'POWER4',
    badge: '📱 พิเศษลูกค้า AIS ลด 200.-',
    image: 'https://images.unsplash.com/photo-1563770660941-20978e870e26?w=600&auto=format&fit=crop&q=80',
    active: true,
    recommendedFor: 'ลูกค้ามือถือ AIS รายเดือนที่ต้องการแพ็กเกจสุดคุ้มครบทั้งบ้านและนอกบ้าน',
    tvIncluded: true,
  },
  {
    id: 'pkg-net-combo-gang',
    name: 'Net Combo Gang (1 Gbps / 500 Mbps) + VIP All-in-One',
    slug: 'net-combo-gang-vip',
    price: 899,
    originalPrice: 1099,
    download_speed: 1000,
    upload_speed: 500,
    contract_month: 24,
    installation_fee: 0,
    description: 'แพ็กเกจบันเทิงขั้นสุด! เน็ต 1Gbps + Mesh 2 ตัว + PLAYBOX + Max + VIU + iQIYI + WeTV + ซิม 5G 20GB (ราคาพิเศษลูกค้า AIS)',
    features: [
      'ความเร็ว 1,000 / 500 Mbps',
      'ฟรี! Mesh WiFi 6 จำนวน 2 ตัว',
      'ฟรี! กล่อง AIS PLAYBOX 4K',
      'ฟรี! 4 สตรีมมิ่งชั้นนำ: Max (HBO) + VIU + iQIYI + WeTV',
      'ฟรี! ซิมเน็ตมือถือ AIS 5G ความจุ 20GB/เดือน โทรฟรี 200 นาที',
    ],
    equipment: ['Mesh WiFi 6 Router (2 ตัว)', 'AIS PLAYBOX 4K', 'AIS 5G SIM 20GB'],
    category: 'ENTERTAINMENT',
    badge: '👑 จัดเต็ม 4 แอพดัง',
    image: 'https://images.unsplash.com/photo-1574375927938-d5a98e8ffe85?w=600&auto=format&fit=crop&q=80',
    active: true,
    recommendedFor: 'แฟนซีรีส์ทุกค่าย ทั้งเกาหลี จีน ฝรั่ง และครอบครัวที่ต้องการซิมโทรศัพท์เสริม',
    tvIncluded: true,
  },
  {
    id: 'pkg-power4-starter',
    name: 'POWER4 Starter (500 / 500 Mbps) + Mesh + SIM 5G',
    slug: 'power4-starter-500',
    price: 599,
    originalPrice: 799,
    download_speed: 500,
    upload_speed: 500,
    contract_month: 24,
    installation_fee: 0,
    description: 'ครบเครื่องเรื่องเน็ตบ้านและเน็ตมือถือ ได้เราเตอร์ Mesh WiFi 6 สัญญาณทะลุผนัง พร้อมซิม AIS 5G 10GB',
    features: [
      'ความเร็ว 500/500 Mbps สปีดสมดุล',
      'ฟรี! Mesh WiFi 6 Router 1-2 ตัว กระจายสัญญาณรอบบ้าน',
      'ฟรี! ซิม AIS 5G 10GB/เดือน พร้อมโทรฟรีในเครือข่าย',
      'ฟรี! AIS PLAY พร้อมช่องรายการพรีเมียม',
      'ฟรี! ค่าติดตั้งและเดินสาย 4,800 บาท',
    ],
    equipment: ['Mesh WiFi 6 Router', 'AIS 5G SIM 10GB', 'ONT'],
    category: 'POWER4',
    badge: '⚡ Power4 สุดฮิต',
    image: 'https://images.unsplash.com/photo-1544716278-ca5e3f4abd8c?w=600&auto=format&fit=crop&q=80',
    active: true,
    recommendedFor: 'ครอบครัวที่ต้องการเน็ตบ้านพร้อมซิมเล่นเน็ตนอกบ้านในบิลเดียว',
    tvIncluded: false,
  },
  {
    id: 'pkg-supermesh-2g-1g',
    name: 'SuperMESH Plus 2 Gbps / 1 Gbps (Dual Router)',
    slug: 'supermesh-plus-2gbps',
    price: 1099,
    originalPrice: 1499,
    download_speed: 2000,
    upload_speed: 1000,
    contract_month: 24,
    installation_fee: 0,
    description: 'เทคโนโลยีเน็ตบ้าน 2Gbps รายแรกในไทย ความเร็วสูงสุด 2,000 Mbps พร้อมเราเตอร์ Mesh WiFi 6 สองตัว กระจายสัญญาณความเร็วแสง',
    features: [
      'ความเร็วแสง 2,000 Mbps / 1,000 Mbps (2Gbps/1Gbps)',
      'ฟรี! เราเตอร์เกรดเรือธง 2Gbps Mesh WiFi 6 จำนวน 2 ตัว',
      'ฟรี! กล่อง AIS PLAYBOX 4K + สิทธิ์ชม VIU Premium & beIN SPORTS',
      'ฟรี! ค่าแรกเข้าและค่าติดตั้ง 4,800 บาท',
      'การันตีการแก้ไขปัญหาภายใน 3 ชั่วโมงตลอด 24 ชม.',
    ],
    equipment: ['2Gbps Dual Mesh WiFi 6 Routers (2 ตัว)', 'AIS PLAYBOX 4K', '2.5G Ultra ONT'],
    category: 'POPULAR',
    badge: '🚀 สปีดสูงสุด 2 Gbps',
    image: 'https://images.unsplash.com/photo-1550751827-4bd374c3f58b?w=600&auto=format&fit=crop&q=80',
    active: true,
    recommendedFor: 'บ้านขนาดใหญ่ ผู้ใช้อุปกรณ์จำนวนมาก ครีเอเตอร์ตัดต่อวิดีโอ 8K และคอเกมระดับโปร',
    tvIncluded: true,
  },
  {
    id: 'pkg-condo-starter-269',
    name: 'Condo & Dorm Starter (50 / 20 Mbps)',
    slug: 'condo-dorm-starter-269',
    price: 269,
    originalPrice: 399,
    download_speed: 50,
    upload_speed: 20,
    contract_month: 12,
    installation_fee: 0,
    description: 'เน็ตไฟเบอร์ราคาประหยัดที่สุดสำหรับคอนโดและหอพัก เริ่มต้นเพียงเดือนละ 269 บาท (ลดเพิ่ม 100 บ. นาน 8 รอบบิล)',
    features: [
      'ความเร็ว 50 Mbps / 20 Mbps ไฟเบอร์ออพติกแท้',
      'ฟรี! เราเตอร์ Dual Band WiFi พร้อมติดตั้ง',
      'สัญญาเพียง 12 เดือน ยืดหยุ่นสำหรับผู้เช่าคอนโด',
      'ฟรี! ค่าติดตั้งและยืมอุปกรณ์ตลอดอายุสัญญา',
    ],
    equipment: ['Dual Band WiFi Router', 'Compact ONU'],
    category: 'CONDO',
    badge: '💰 เริ่มต้น 269.-/ด.',
    image: 'https://images.unsplash.com/photo-1502672260266-1c1ef2d93688?w=600&auto=format&fit=crop&q=80',
    active: true,
    recommendedFor: 'ผู้พักอาศัยคอนโด หอพัก อพาร์ทเมนต์ นักศึกษา และผู้ใช้งานคนเดียว',
    tvIncluded: false,
  },
  {
    id: 'pkg-condo-ultra-300',
    name: 'Condo Ultra Fibre (300 / 300 Mbps)',
    slug: 'condo-ultra-fibre-300',
    price: 399,
    originalPrice: 499,
    download_speed: 300,
    upload_speed: 300,
    contract_month: 12,
    installation_fee: 0,
    description: 'เน็ตคอนโดความเร็วสูง 300/300 Mbps โปรโมชั่นพิเศษลด 100 บาทนาน 8 รอบบิล (จาก 499 เหลือ 399)',
    features: [
      'ความเร็วสมดุล 300 Mbps / 300 Mbps',
      'ฟรี! เราเตอร์ WiFi 6 ประสิทธิภาพสูง รองรับหลายอุปกรณ์',
      'ฟรี! ค่าช่างติดตั้งและเดินสายในห้อง',
      'ดูคลิป 4K สตรีมมิ่ง ประชุมออนไลน์ได้ลื่นไหล',
    ],
    equipment: ['WiFi 6 Smart Router (1 ตัว)', 'ONU Unit'],
    category: 'CONDO',
    badge: '🏢 ฮิตสุดในคอนโด',
    image: 'https://images.unsplash.com/photo-1545324418-cc1a3fa10c00?w=600&auto=format&fit=crop&q=80',
    active: true,
    recommendedFor: 'คอนโดมิเนียมและทาวน์โฮม 1-3 คนที่ต้องการเน็ตแรงในราคาประหยัด',
    tvIncluded: false,
  },
  {
    id: 'pkg-home-fiber-lan-10g',
    name: 'Home Fiber LAN 2Gbps / 10Gbps Ready (สายใยแก้วโปร่งแสง)',
    slug: 'home-fiber-lan-transparent',
    price: 1399,
    originalPrice: 1899,
    download_speed: 2000,
    upload_speed: 2000,
    contract_month: 24,
    installation_fee: 0,
    description: 'นวัตกรรมสายใยแก้วโปร่งแสง (Transparent Optical Fiber) ขนาดเล็กเท่าเส้นผม วิ่งเน็ต 2Gbps-10Gbps ทะลุทุกห้องในบ้านอย่างไร้รอยต่อ',
    features: [
      'ความเร็ว 2,000 Mbps / 2,000 Mbps ทั่วทุกห้องในบ้าน',
      'เดินสายใยแก้วโปร่งแสงขนาดไมโคร ไม่บดบังทัศนียภาพของบ้าน',
      'ฟรี! เราเตอร์ AI Smart WiFi 6/7 สำหรับทุกจุดติดตั้ง',
      'อายุการใช้งานสายไฟเบอร์ยาวนานถึง 30 ปี',
      'ทีมวิศวกรเฉพาะทางออกแบบระบบเน็ตเวิร์กให้ถึงบ้าน',
    ],
    equipment: ['AI Smart Gateway 10G', 'Transparent Fiber LAN Multi-Room Nodes', 'WiFi 6/7 Satellite'],
    category: 'SMARTHOME',
    badge: '💎 นวัตกรรมสายใส 10Gbps',
    image: 'https://images.unsplash.com/photo-1600585154340-be6161a56a0c?w=600&auto=format&fit=crop&q=80',
    active: true,
    recommendedFor: 'บ้านเดี่ยวหรู บ้าน 2-4 ชั้น โฮมออฟฟิศระดับพรีเมียมที่ต้องการความเร็วเต็มสปีดทุกห้อง',
    tvIncluded: true,
  },
  {
    id: 'pkg-gamer-extreme',
    name: 'Gamer Extreme Power (1000 / 500 Mbps) VIP Ping',
    slug: 'gamer-extreme-power-1000',
    price: 899,
    originalPrice: 1099,
    download_speed: 1000,
    upload_speed: 500,
    contract_month: 24,
    installation_fee: 0,
    description: 'ออกแบบพิเศษเพื่อคอเกมมิ่งและสตรีมเมอร์ พร้อมฟีเจอร์แยกท่อเกม (Dual Band Game Turbo) ปิงต่ำ เซิร์ฟเวอร์ในและต่างประเทศเสถียรสุด',
    features: [
      'ความเร็ว 1000/500 Mbps พร้อม Dual Game Route',
      'เราเตอร์ WiFi 6 Tri-Band Gaming Class',
      'ค่า Latency ต่ำพิเศษ (Ultra-Low Ping 1-5ms)',
      'ฟรี! Public IPv4 & IPv6 เหมาะสำหรับตั้ง Server/Port Forward',
      'รับสิทธิพิเศษและส่วนลดเติมเกมชั้นนำ',
    ],
    equipment: ['Gaming WiFi 6 Tri-Band Router', 'High Speed ONU'],
    category: 'GAMER',
    badge: '⚡ คอเกม & สตรีมเมอร์',
    image: 'https://images.unsplash.com/photo-1542751371-adc38448a05e?w=600&auto=format&fit=crop&q=80',
    active: true,
    recommendedFor: 'เกมเมอร์, สตรีมเมอร์ Twitch/YouTube, นักแข่ง Esports และดาวน์โหลดไฟล์ใหญ่',
    tvIncluded: false,
  },
];

export const INITIAL_PROMOTIONS: PromotionItem[] = [
  {
    id: 'promo-1',
    title: 'ติดตั้งวันนี้ ฟรี! ค่าแรกเข้าและค่าเดินสาย มูลค่า 4,800 บาท',
    subtitle: 'สิทธิพิเศษเฉพาะลูกค้าที่สมัครผ่านเว็บไซต์ AIS Fibre Net999 เท่านั้น',
    description: 'รับสิทธิ์ติดตั้งฟรีทุกขั้นตอน พร้อมยืมอุปกรณ์เราเตอร์ WiFi 6 ประสิทธิภาพสูงตลอดอายุการใช้งาน ไม่ต้องจ่ายค่าประกันอุปกรณ์',
    image: 'https://images.unsplash.com/photo-1558494949-ef010cbdcc31?w=800&auto=format&fit=crop&q=80',
    start_date: '2026-01-01',
    end_date: '2026-12-31',
    cta_text: 'เช็กพื้นที่รับสิทธิ์เลย',
    cta_link: '/check-area',
    badge: '⚡ สิทธิพิเศษจำกัดเวลา',
    active: true,
    highlight: true,
  },
  {
    id: 'promo-2',
    title: 'อัปเกรดความเร็วเป็น 1Gbps ราคาพิเศษเพียง 599.-/เดือน',
    subtitle: 'คุ้มกว่าเดิม ด้วยความเร็วแรงระดับกิกะบิต',
    description: 'สำหรับลูกค้าใหม่ที่ย้ายค่ายมาใช้ AIS Fibre รับส่วนลดพิเศษทันที 200 บาท/เดือน นาน 24 รอบบิล',
    image: 'https://images.unsplash.com/photo-1544717305-2782549b5136?w=800&auto=format&fit=crop&q=80',
    start_date: '2026-01-01',
    end_date: '2026-12-31',
    cta_text: 'ดูแพ็กเกจโปรย้ายค่าย',
    cta_link: '/packages',
    badge: '🎁 โปรย้ายค่ายสุดฮิต',
    active: true,
    highlight: true,
  },
  {
    id: 'promo-3',
    title: 'ฟรี! กล่อง AIS PLAYBOX พร้อมแพ็กเกจ VIU & กีฬา 24 เดือน',
    subtitle: 'เปลี่ยนทีวีธรรมดาให้เป็นสมาร์ททีวี 4K',
    description: 'เมื่อสมัครแพ็กเกจตั้งแต่ 599 บาทขึ้นไป รับฟรีกล่องทีวีแอนดรอยด์ 4K เพลิดเพลินกับหนัง ซีรีส์ และฟุตบอลระดับโลก',
    image: 'https://images.unsplash.com/photo-1593784991095-a205069470b6?w=800&auto=format&fit=crop&q=80',
    start_date: '2026-01-01',
    end_date: '2026-12-31',
    cta_text: 'สมัครพร้อมรับกล่องทีวี',
    cta_link: '/apply',
    badge: '🎬 บันเทิงเต็มอิ่ม',
    active: true,
    highlight: false,
  },
];

export const INITIAL_LEADS: LeadItem[] = [];

export const INITIAL_APPLICATIONS: ApplicationItem[] = [];

export const INITIAL_EQUIPMENT: EquipmentItem[] = [
  {
    id: 'eq-1',
    name: 'WiFi 6 Smart Mesh Router AX3000',
    category: 'WIFI_6',
    image: 'https://images.unsplash.com/photo-1544716278-ca5e3f4abd8c?w=600&auto=format&fit=crop&q=80',
    description: 'เราเตอร์เทคโนโลยี WiFi 6 มาตรฐานใหม่อัจฉริยะ รองรับแบนด์วิดท์ 160MHz ส่งสัญญาณทะลุสิ่งกีดขวางได้ดียิ่งขึ้น รองรับการต่อ Mesh ไร้รอยต่อ',
    highlights: [
      'ความเร็วรวมสูงสุด 3000 Mbps (Dual Band)',
      'เทคโนโลยี OFDMA & MU-MIMO เชื่อมต่อได้พร้อมกันกว่า 50 เครื่อง',
      'เสาสัญญาณภายใน High-Gain 4 ต้น',
      'รองรับ Seamless Roaming เดินทั่วบ้านไม่หลุด',
    ],
    suitable_for: 'บ้านเดี่ยว ทาวน์โฮม 2-3 ชั้น คอนโดขนาดใหญ่ และบ้านที่มีอุปกรณ์ IoT หลายชิ้น',
    supported_packages: ['Super MESH WiFi Pro 1000/1000', 'Home PowerBoost 500/500', 'Smart Home 1099'],
    specs: {
      'มาตรฐานสัญญาณ': 'Wi-Fi 6 (802.11ax/ac/n/a 5GHz, 802.11ax/n/b/g 2.4GHz)',
      'พอร์ตเชื่อมต่อ': '1x Gigabit WAN + 3x Gigabit LAN',
      'ความปลอดภัย': 'WPA3-SAE, SPI Firewall, IPv6 Support',
      'ขนาดตัวเครื่อง': '210 x 135 x 38 มม.',
    },
  },
  {
    id: 'eq-2',
    name: 'WiFi 7 Tri-Band HyperStream BE9300',
    category: 'WIFI_7',
    image: 'https://images.unsplash.com/photo-1558494949-ef010cbdcc31?w=600&auto=format&fit=crop&q=80',
    description: 'สุดยอดเราเตอร์เจเนอเรชันถัดไป WiFi 7 เพิ่มช่องสัญญาณ 6GHz ความกว้าง 320MHz และเทคโนโลยี Multi-Link Operation (MLO) รับส่งข้อมูลหลายคลื่นพร้อมกัน',
    highlights: [
      'ความเร็วทะลุ 9300 Mbps บน 3 คลื่นความถี่ (2.4GHz + 5GHz + 6GHz)',
      'พอร์ต Multi-Gigabit 2.5Gbps WAN/LAN รองรับสปีด 2Gbps แท้',
      'ลด Latency ลงกว่า 80% เหมาะสำหรับ VR, Cloud Gaming, และงานสตรีมมิ่งสด',
      'ระบบกระจายสัญญาณ Beamforming อัตโนมัติค้นหาตำแหน่งอุปกรณ์',
    ],
    suitable_for: 'สายเทค สตรีมเมอร์ ครีเอเตอร์ตัดต่อไฟล์ 8K และคอเกมระดับโปร',
    supported_packages: ['WiFi 7 Next-Gen HyperSpeed 1499'],
    specs: {
      'มาตรฐานสัญญาณ': 'Wi-Fi 7 (802.11be, 320MHz bandwidth, 4K-QAM)',
      'พอร์ตเชื่อมต่อ': '1x 2.5Gbps WAN + 1x 2.5Gbps LAN + 3x Gigabit LAN',
      'เทคโนโลยีพิเศษ': 'Multi-Link Operation (MLO), Preamble Puncturing',
      'หน่วยประมวลผล': 'Quad-Core 2.0GHz Processor + 1GB RAM',
    },
  },
  {
    id: 'eq-3',
    name: 'AIS PLAYBOX 4K Android TV Gen 3',
    category: 'AIS_PLAYBOX',
    image: 'https://images.unsplash.com/photo-1593784991095-a205069470b6?w=600&auto=format&fit=crop&q=80',
    description: 'กล่องรับสัญญาณความบันเทิงระดับโลก คมชัด 4K Ultra HD ขับเคลื่อนด้วยระบบปฏิบัติการ Android TV แท้ พร้อมรีโมทคอนโทรลสั่งการด้วยเสียงภาษาไทย',
    highlights: [
      'ความละเอียดคมชัดสูงสุด 4K UHD 60fps รองรับ HDR10+ และ Dolby Audio',
      'รีโมท Google Assistant สั่งงานด้วยเสียงภาษาไทย ค้นหาหนังง่าย',
      'ดาวน์โหลดแอปยอดนิยมได้จาก Google Play Store (YouTube, Netflix, Disney+, Prime)',
      'เชื่อมต่อได้ทั้งพอร์ต LAN และ WiFi 5GHz ไหลลื่นไม่สะดุด',
    ],
    suitable_for: 'ทุกครอบครัวที่ต้องการเปลี่ยนทีวีให้เป็นศูนย์รวมความบันเทิงครบวงจร',
    supported_packages: ['Super MESH WiFi Pro 1000/1000', 'Entertainment Max 599', 'Smart Home 1099'],
    specs: {
      'ความละเอียด': '3840 x 2160 (4K UHD) HDR10',
      'ระบบปฏิบัติการ': 'Android TV Official OS',
      'การเชื่อมต่อ': 'HDMI 2.1, USB 2.0/3.0, Optical Audio, RJ45 LAN, Bluetooth 5.0',
      'ระบบเสียง': 'Dolby Digital Plus / Surround 5.1 Passthrough',
    },
  },
  {
    id: 'eq-4',
    name: 'Gigabit GPON Optical Network Unit (ONU)',
    category: 'ONU',
    image: 'https://images.unsplash.com/photo-1544717305-2782549b5136?w=600&auto=format&fit=crop&q=80',
    description: 'อุปกรณ์แปลงสัญญาณแสงไฟเบอร์ออปติกแท้ แปลงความเร็วแสงจากสายใยแก้วเป็นสัญญาณเน็ตความเร็วสูงระดับ Gigabit ประสิทธิภาพทนทาน 24 ชม.',
    highlights: [
      'รองรับความเร็วขาเข้า Fibre Optic สูงสุด 2.5Gbps Downstream / 1.25Gbps Upstream',
      'ประหยัดพลังงาน ระบายความร้อนได้ดีเยี่ยม เปิดต่อเนื่องได้ตลอดทั้งปี',
      'ระบบ Optical Power Monitoring ตรวจสอบคุณภาพสายสัญญาณเรียลไทม์',
    ],
    suitable_for: 'อุปกรณ์มาตรฐานที่ติดตั้งฟรีให้แก่ลูกค้า AIS Fibre ทุกแพ็กเกจ',
    supported_packages: ['ทุกแพ็กเกจของ AIS Fibre'],
    specs: {
      'หัวเชื่อมต่อแสง': 'SC/APC Single-Mode Fiber Port',
      'ระยะสายใยแก้ว': 'รองรับระยะสูงสุด 20 กิโลเมตรจากจุดชุมสาย',
      'ไฟสัญญาณ': 'Power, PON, LOS, LAN 1-4, WAN',
    },
  },
  {
    id: 'eq-5',
    name: 'Mesh WiFi Expansion Node Dual-Band',
    category: 'MESH_WIFI',
    image: 'https://images.unsplash.com/photo-1544716278-ca5e3f4abd8c?w=600&auto=format&fit=crop&q=80',
    description: 'ตัวขยายสัญญาณ Mesh WiFi ไร้สาย เชื่อมต่อกับเราเตอร์ตัวหลักโดยอัตโนมัติ กระจายสัญญาณไปยังจุดอับสัญญาณ เช่น ห้องนอนชั้นบน โรงรถ หรือสวนหลังบ้าน',
    highlights: [
      'ขยายพื้นที่ครอบคลุมเพิ่มขึ้น 120-150 ตร.ม. ต่อตัว',
      'ชื่อ WiFi (SSID) เดียวกันทั้งบ้าน สลับจุดเชื่อมต่ออัตโนมัติแบบไร้รอยต่อ',
      'ติดตั้งง่ายเพียงกดปุ่ม WPS เชื่อมต่ออัตโนมัติใน 1 นาที',
    ],
    suitable_for: 'บ้านที่มีมุมอับสัญญาณ ผนังปูนหนา หรือบ้านหลายชั้นที่ต้องการสัญญาณเต็มทุกตารางนิ้ว',
    supported_packages: ['Super MESH WiFi Pro 1000/1000', 'Smart Home & CCTV Ultimate 1099'],
    specs: {
      'พื้นที่ครอบคลุม': '120-150 ตารางเมตร',
      'การเชื่อมต่อ Backhaul': 'Wireless Mesh 5GHz หรือ Dedicated Ethernet Cable',
      'เสาสัญญาณ': 'Internal High Gain Antenna x 4',
    },
  },
];

export const INITIAL_ARTICLES: ArticleItem[] = [
  {
    id: 'art-1',
    title: 'วิธีเลือกแพ็กเกจเน็ตบ้านให้เหมาะกับครอบครัว สปีดเท่าไหร่ถึงพอดี?',
    slug: 'how-to-choose-home-internet-speed',
    category: 'INTERNET',
    cover_image: 'https://images.unsplash.com/photo-1581092160607-ee22621dd758?w=800&auto=format&fit=crop&q=80',
    author: 'ทีมงานวิศวกร AIS Fibre Net999',
    published_date: '2026-08-25',
    reading_time: '4 นาที',
    excerpt: 'ไขข้อข้องใจเรื่องความเร็วเน็ตบ้าน 500/500 vs 1000/1000 Mbps ต่างกันแค่ไหน มีคนอยู่บ้านกี่คนต้องใช้แพ็กเกจอะไรให้คุ้มค่าที่สุด',
    content: `ในการเลือกติดตั้งอินเทอร์เน็ตบ้าน สิ่งสำคัญที่สุดไม่ใช่การเลือกแพ็กเกจที่แพงที่สุด แต่คือการเลือก **ความเร็วและฟังก์ชันที่ตอบโจทย์พฤติกรรมของสมาชิกในบ้านอย่างแท้จริง**

### 1. ประเมินจำนวนผู้ใช้งานในบ้าน
* **1-2 คน (การใช้งานทั่วไป):** ความเร็ว 200 - 500 Mbps เพียงพอสำหรับการดู YouTube FHD, ใช้งาน Social Media, ส่งอีเมล และ Work From Home ทั่วไป
* **3-5 คน (ครอบครัวขนาดกลาง):** แนะนำ 500/500 หรือ 1000/500 Mbps รองรับการสตรีม Netflix 4K พร้อมกันหลายเครื่อง และเล่นเกมออนไลน์โดยไม่มีสะดุด
* **6 คนขึ้นไป หรือบ้านหลังใหญ่:** ควรเลือก 1000/1000 Mbps (1Gbps) พร้อมเราเตอร์ Mesh WiFi กระจายสัญญาณรอบบ้าน

### 2. รูปแบบกิจกรรมหลัก
หากในบ้านมีคน **สตรีมเกม, ไลฟ์สดขายของ, หรือสำรองข้อมูลขึ้น Cloud เป็นประจำ** ควรเลือกแพ็กเกจที่มีค่าความเร็ว **Upload สูง (500-1000 Mbps)** เพื่อให้การส่งไฟล์รวดเร็วและไม่มีอาการกระตุก`,
    published: true,
    views: 1240,
    seo_title: 'วิธีเลือกความเร็วเน็ตบ้านให้เหมาะกับครอบครัว - AIS Fibre Net999',
    meta_description: 'แนะนำวิธีเลือกแพ็กเกจเน็ตบ้าน AIS Fibre คำนวณความเร็ว Mbps ที่เหมาะกับสมาชิกในครอบครัวและลักษณะการใช้งาน',
    keywords: ['เน็ตบ้าน', 'เลือกเน็ตบ้าน', 'AIS Fibre', 'ความเร็วเน็ต', '500Mbps', '1Gbps'],
  },
  {
    id: 'art-2',
    title: 'Mesh WiFi คืออะไร? ทำไมบ้าน 2-3 ชั้นควรมีติดไว้',
    slug: 'what-is-mesh-wifi-guide',
    category: 'WIFI',
    cover_image: 'https://images.unsplash.com/photo-1544716278-ca5e3f4abd8c?w=800&auto=format&fit=crop&q=80',
    author: 'กิตติพงษ์ เทคกูรู',
    published_date: '2026-08-20',
    reading_time: '5 นาที',
    excerpt: 'หมดปัญหาสัญญาณ WiFi ไปไม่ถึงชั้นบนหรือหลุดบ่อยด้วยเทคโนโลยี Mesh WiFi สัญญาณแรงทั่วบ้านด้วยชื่อเดียว (Single SSID)',
    content: `หลายท่านที่อยู่บ้านทาวน์โฮมหรือบ้านเดี่ยว 2-3 ชั้น มักพบปัญหาว่า **อยู่ชั้นล่างเน็ตวิ่งเต็ม 1Gbps แต่พอเดินขึ้นชั้น 2-3 สัญญาณเหลือ 1 ขีดและเน็ตหมุน**

### Mesh WiFi แก้ปัญหานี้ได้อย่างไร?
Mesh WiFi เป็นการทำงานร่วมกันของเร้าเตอร์ 2 ตัวขึ้นไปที่เชื่อมต่อถึงกันเป็นโครงข่ายร่างแห (Mesh Topology)

1. **ชื่อเดียวทั้งบ้าน (Single SSID):** ไม่ต้องคอยกดสลับชื่อ WiFi เมื่อเดินขึ้นบันได
2. **Seamless Roaming:** ระบบจะส่งต่อสัญญาณให้อุปกรณ์ของคุณไปยังเราเตอร์ตัวที่ใกล้ที่สุดโดยไม่หลุดแม้แต่เสี้ยววินาที
3. **ทะลุสิ่งกีดขวาง:** ลดจุดอับสัญญาณหลังกำแพงหรือมุมอับได้ 100%`,
    published: true,
    views: 980,
    seo_title: 'Mesh WiFi คืออะไร ทำไมบ้านหลายชั้นต้องใช้ - AIS Fibre Net999',
    meta_description: 'ทำความรู้จัก Mesh WiFi เทคโนโลยีกระจายสัญญาณทั่วบ้าน หมดปัญหาสัญญาณอ่อนในบ้าน 2-3 ชั้น',
    keywords: ['Mesh WiFi', 'เราเตอร์', 'WiFi 6', 'กระจายสัญญาณ', 'เน็ตบ้าน AIS'],
  },
  {
    id: 'art-3',
    title: 'เคล็ดลับเล่นเกมออนไลน์ปิงต่ำ (Low Ping) ไม่แลค ไม่หลุดช็อตสำคัญ',
    slug: 'gaming-low-latency-tips',
    category: 'GAMING',
    cover_image: 'https://images.unsplash.com/photo-1538481199705-c710c4e965fc?w=800&auto=format&fit=crop&q=80',
    author: 'ทีมงาน Esports Support',
    published_date: '2026-08-15',
    reading_time: '3 นาที',
    excerpt: 'เทคนิคตั้งค่าเราเตอร์และเลือกคู่สายไฟเบอร์เพื่อลดค่า Latency ให้เหลือเพียง 1-5ms พร้อมฟีเจอร์ Gaming Bandwidth จาก AIS Fibre',
    content: `สำหรับสาย Gaming ไม่ว่าจะเป็น Valorant, ROV, PUBG, FIFA หรือ Dota 2 สิ่งที่ตัดสินแพ้ชนะไม่ใช่แค่ความเร็วในการดาวน์โหลด แต่คือ **Latency (Ping) และ Jitter (ความนิ่งของสัญญาณ)**

แพ็กเกจ Gamer ของ AIS Fibre มีการจัดสรรเส้นทางพิเศษ (Optimized Gaming Routing) ไปยังเซิร์ฟเวอร์เกมชั้นนำในสิงคโปร์ ฮ่องกง และญี่ปุ่น ทำให้ปิงต่ำและเสถียรที่สุดในไทย`,
    published: true,
    views: 1560,
    seo_title: 'เคล็ดลับเล่นเกมออนไลน์ปิงต่ำ ลดแลค - AIS Fibre Net999',
    meta_description: 'วิธีลดค่า Ping สำหรับคอเกม พร้อมฟีเจอร์แยกท่อเกมมิ่งจากเน็ตบ้าน AIS Fibre',
    keywords: ['เน็ตเกมมิ่ง', 'ลดปิง', 'Low Ping', 'AIS Fibre Gamer', 'Valorant', 'Esports'],
  },
  {
    id: 'art-4',
    title: 'WiFi 7 มาแล้ว! มีอะไรใหม่ ดีกว่า WiFi 6 อย่างไรบ้าง?',
    slug: 'wifi-7-vs-wifi-6-comparison',
    category: 'WIFI',
    cover_image: 'https://images.unsplash.com/photo-1558494949-ef010cbdcc31?w=800&auto=format&fit=crop&q=80',
    author: 'วิศวกรเครือข่าย',
    published_date: '2026-08-10',
    reading_time: '6 นาที',
    excerpt: 'เจาะลึกมาตรฐาน WiFi 7 (802.11be) ที่ให้สปีดเร็วขึ้นถึง 4.8 เท่า พร้อมช่องสัญญาณกว้าง 320MHz และ MLO เทคโนโลยีรับส่งหลายคลื่นพร้อมกัน',
    content: `WiFi 7 เป็นก้าวกระโดดครั้งใหญ่ที่สุดของเทคโนโลยีไร้สายในรอบทศวรรษ

* **ช่องสัญญาณกว้าง 320 MHz:** กว้างกว่า WiFi 6 สองเท่า จุข้อมูลได้มหาศาล
* **Multi-Link Operation (MLO):** สมาร์ทโฟนสามารถรับส่งสัญญาณคลื่น 5GHz และ 6GHz ได้พร้อมกัน
* **4K-QAM:** อัดแน่นบิตข้อมูลได้หนาแน่นขึ้น 20% ทำให้เปิดวิดีโอ 8K หรือสตรีมสดได้ทันใจ`,
    published: true,
    views: 2100,
    seo_title: 'WiFi 7 คืออะไร ดีกว่า WiFi 6 อย่างไร - AIS Fibre Net999',
    meta_description: 'เปรียบเทียบความแตกต่างระหว่าง WiFi 7 และ WiFi 6 เทคโนโลยีไร้สายแห่งอนาคต',
    keywords: ['WiFi 7', 'WiFi 6', 'ความเร็วเน็ต', 'เราเตอร์รุ่นใหม่', 'AIS Fibre'],
  },
  {
    id: 'art-5',
    title: 'ติดตั้งกล้องวงจรปิด Smart Home ให้เสถียร ต้องใช้เน็ตบ้านแบบไหน?',
    slug: 'smart-home-cctv-internet-guide',
    category: 'SMART_HOME',
    cover_image: 'https://images.unsplash.com/photo-1558002038-1055907df827?w=800&auto=format&fit=crop&q=80',
    author: 'ผู้เชี่ยวชาญสมาร์ทโฮม',
    published_date: '2026-08-05',
    reading_time: '4 นาที',
    excerpt: 'คำแนะนำการติดตั้งระบบกล้องวงจรปิดไร้สาย CCTV และอุปกรณ์ IoT ในบ้าน ให้ดูภาพย้อนหลังลื่นไหล 24 ชั่วโมง โดยสัญญาณไม่ชนกัน',
    content: `อุปกรณ์ Smart Home เช่น กล้องวงจรปิด หลอดไฟอัจฉริยะ และสวิตช์อัตโนมัติ ต้องการ **ความเสถียรของสัญญาณ WiFi 2.4GHz และความเร็วอัปโหลดที่คงที่** เพื่อส่งภาพบันทึกขึ้น Cloud แบบเรียลไทม์`,
    published: true,
    views: 890,
    seo_title: 'ติดตั้งกล้องวงจรปิด Smart Home เลือกเน็ตบ้านแบบไหนดี',
    meta_description: 'คู่มือเลือกเน็ตบ้านสำหรับบ้านที่มีกล้องวงจรปิด CCTV และอุปกรณ์ Smart Home IoT',
    keywords: ['Smart Home', 'CCTV', 'กล้องวงจรปิด', 'เน็ตบ้าน', 'IoT'],
  },
];

export const INITIAL_FAQS: FAQItem[] = [
  {
    id: 'faq-1',
    question: 'AIS Fibre คืออะไร และแตกต่างจากเน็ตทั่วไปอย่างไร?',
    answer: 'AIS Fibre คือบริการอินเทอร์เน็ตความเร็วสูงผ่านโครงข่ายสายใยแก้วนำแสง (Pure Fibre Optic 100%) ส่งสัญญาณด้วยแสง ทำให้ได้ความเร็วที่เสถียร ทนทานต่อสภาพอากาศ ฝนตกฟ้าร้องสัญญาณไม่ดรอป ค่าความหน่วง (Latency) ต่ำ เหมาะกับทั้งการทำงาน สตรีมมิ่ง และเล่นเกม',
    category: 'GENERAL',
    order: 1,
    popular: true,
  },
  {
    id: 'faq-2',
    question: 'สมัครติดตั้ง AIS Fibre ใช้เวลากี่วันถึงจะได้ติดตั้ง?',
    answer: 'หลังจากส่งข้อมูลและเจ้าหน้าที่ตรวจสอบคู่สายเรียบร้อย โดยทั่วไปจะสามารถนัดหมายช่างเข้าติดตั้งได้ภายใน 24 - 48 ชั่วโมง (1-2 วันทำการ) หรือสามารถเลือกวันและเวลาที่ท่านสะดวกได้ตามต้องการ',
    category: 'INSTALLATION',
    order: 2,
    popular: true,
  },
  {
    id: 'faq-3',
    question: 'ตรวจสอบพื้นที่ให้บริการ (Coverage Check) อย่างไร?',
    answer: 'ท่านสามารถกรอกข้อมูลที่อยู่ เช่น จังหวัด อำเภอ ตำบล บ้านเลขที่ หรือปักหมุดพิกัด GPS บนหน้าเว็บไซต์ "ตรวจสอบพื้นที่" ของเราได้ทันที เจ้าหน้าที่จะทำการเช็กคู่สาย DP เสาไฟฟ้า และติดต่อกลับแจ้งผลภายใน 15-30 นาทีในเวลาทำการ',
    category: 'COVERAGE',
    order: 3,
    popular: true,
  },
  {
    id: 'faq-4',
    question: 'สมัครติดตั้งต้องใช้เอกสารอะไรบ้าง?',
    answer: 'สำหรับบุคคลธรรมดา ใช้เพียงภาพถ่าย "บัตรประจำตัวประชาชน" ตัวจริงที่มีชื่อตรงกับผู้สมัคร (สามารถขีดคร่อม "ใช้สำหรับสมัคร AIS Fibre เท่านั้น") สำหรับนิติบุคคลใช้หนังสือรับรองบริษัทอายุไม่เกิน 3 เดือนและสำเนาบัตรประชาชนกรรมการผู้มีอำนาจลงนาม',
    category: 'DOCUMENTS',
    order: 4,
    popular: true,
  },
  {
    id: 'faq-5',
    question: 'มีค่าติดตั้งหรือค่าอุปกรณ์แรกเข้าหรือไม่?',
    answer: 'ฟรี! ค่าแรกเข้าและค่าติดตั้งเดินสายไฟเบอร์ออปติกภายนอกมูลค่า 4,800 บาท สำหรับลูกค้าที่สมัครแพ็กเกจตามเงื่อนไข พร้อมฟรีค่าสิทธิ์ยืมอุปกรณ์เราเตอร์ WiFi 6 และกล่อง AIS PLAYBOX ตลอดอายุสัญญาการใช้งาน',
    category: 'PACKAGE',
    order: 5,
    popular: true,
  },
  {
    id: 'faq-6',
    question: 'ระยะเวลาสัญญามีกี่เดือน?',
    answer: 'ระยะเวลาสัญญามาตรฐานมีตั้งแต่ 12 เดือน หรือ 24 เดือน ขึ้นอยู่กับแพ็กเกจและสิทธิพิเศษโปรโมชั่นที่เลือก โดยแพ็กเกจสัญญา 24 เดือนจะได้รับสิทธิพิเศษและส่วนลดค่าบริการรายเดือนที่คุ้มค่ากว่า',
    category: 'PACKAGE',
    order: 6,
    popular: true,
  },
  {
    id: 'faq-7',
    question: 'หากย้ายบ้านหรือย้ายที่อยู่ สามารถย้ายจุดติดตั้งได้ไหม?',
    answer: 'สามารถย้ายสถานที่ติดตั้งได้ฟรี ไม่มีค่าบริการ เมื่อใช้งานครบ 6 เดือนขึ้นไป เพียงแจ้งเจ้าหน้าที่ล่วงหน้าอย่างน้อย 7-14 วัน เพื่อตรวจสอบคู่สายในพื้นที่แห่งใหม่',
    category: 'INSTALLATION',
    order: 7,
    popular: false,
  },
  {
    id: 'faq-8',
    question: 'สามารถเปลี่ยนหรืออัปเกรดแพ็กเกจความเร็วในภายหลังได้ไหม?',
    answer: 'สามารถปรับเปลี่ยนหรืออัปเกรดแพ็กเกจให้มีความเร็วสูงขึ้นได้ตลอดเวลาผ่านแอป myAIS หรือแจ้งเจ้าหน้าที่ฝ่ายบริการลูกค้าของเรา โดยมีผลรอบบิลถัดไปทันที',
    category: 'PACKAGE',
    order: 8,
    popular: false,
  },
  {
    id: 'faq-9',
    question: 'อุปกรณ์ Router ที่ได้รับมีอะไรบ้าง?',
    answer: 'ท่านจะได้รับอุปกรณ์ Optical Network Unit (ONU) แปลงสัญญาณแสง และเราเตอร์ WiFi 6 หรือ WiFi 7 ตามแพ็กเกจที่เลือก โดยบางแพ็กเกจจะได้รับเราเตอร์ Mesh WiFi เพิ่มอีก 1-2 ตัวเพื่อกระจายสัญญาณทั่วบ้าน',
    category: 'EQUIPMENT',
    order: 9,
    popular: true,
  },
  {
    id: 'faq-10',
    question: 'หากอินเทอร์เน็ตมีปัญหา สามารถติดต่อแจ้งซ่อมได้อย่างไร?',
    answer: 'สามารถติดต่อได้ที่เบอร์โทรศัพท์ 093-551-5442 หรือติดต่อเจ้าหน้าที่ตัวแทนจำหน่าย AIS FIBRE 3 By โฮมไฟเบอร์เนต999 ผ่านทาง LINE: @aisfibrefanclub (เวลาทำการ ทุกวัน 08.00 - 17.00 น.)',
    category: 'TROUBLESHOOT',
    order: 10,
    popular: true,
  },
];

export const INITIAL_BANNERS: BannerItem[] = [
  {
    id: 'banner-1',
    title: 'AIS 3BB FIBRE 3 อนาคตที่มากกว่าเน็ตบ้าน',
    subtitle: 'เร็ว แรง สูงสุด 2,000 Mbps พร้อมเราเตอร์ Wi-Fi 7 และกล่อง AIS PLAYBOX ฟรี!',
    description: 'เน็ตบ้านไฟเบอร์แท้ 100% สัญญาณเสถียร ครอบคลุม 77 จังหวัดทั่วไทย บริการติดตั้งฟรี',
    image: 'https://images.unsplash.com/photo-1544197150-b99a580bb7a8?w=1600&auto=format&fit=crop&q=80',
    badge: '⚡ มาตรฐานใหม่ 2026',
    cta_text: 'เลือกดูแพ็กเกจยอดนิยม',
    cta_link: '/packages',
    link_type: 'INTERNAL',
    position: 'HERO_SLIDER',
    order: 1,
    active: true,
    bg_gradient: 'from-emerald-950/90 via-slate-900/90 to-slate-950/95',
    start_date: '2026-01-01',
    end_date: '2026-12-31',
    created_at: '2026-08-01T08:00:00Z',
  },
  {
    id: 'banner-2',
    title: 'Broadband 24 สปีดแรง 1 Gbps เพียง 499.-',
    subtitle: 'เน็ตบ้านไฟเบอร์แท้ 1000/500 Mbps คุ้มค่าที่สุด ฟรีค่าแรกเข้า & ติดตั้ง 4,800.-',
    description: 'ยืมเราเตอร์ WiFi 6 อัจฉริยะ 1 ตัว สัญญาณนิ่ง เล่นเกม สตรีมหนังไม่มีสะดุด',
    image: 'https://images.unsplash.com/photo-1558494949-ef010cbdcc31?w=1600&auto=format&fit=crop&q=80',
    badge: '🔥 โปรโมชั่นขายดีอันดับ 1',
    cta_text: 'สมัครติดตั้งแพ็กเกจนี้',
    cta_link: '/apply',
    link_type: 'INTERNAL',
    position: 'HERO_SLIDER',
    order: 2,
    active: true,
    bg_gradient: 'from-teal-950/90 via-slate-900/90 to-slate-950/95',
    start_date: '2026-01-01',
    end_date: '2026-12-31',
    created_at: '2026-08-05T08:00:00Z',
  },
  {
    id: 'banner-3',
    title: 'SuperMESH WiFi 7 ไร้จุดอับสัญญาณทั่วบ้าน',
    subtitle: 'เทคโนโลยีใหม่ล่าสุด ช่องสัญญาณ 320MHz ลดความหน่วง เล่นเกมลื่นไหล',
    description: 'พร้อมคู่เราเตอร์ MESH ส่งสัญญาณทะลุผนังปูน เดินเปลี่ยนห้องเน็ตไม่หลุด',
    image: 'https://images.unsplash.com/photo-1511512578047-dfb367046420?w=1600&auto=format&fit=crop&q=80',
    badge: '🚀 Wi-Fi 7 Next-Gen',
    cta_text: 'เช็คพื้นที่ติดตั้งทันที',
    cta_link: '/check-area',
    link_type: 'INTERNAL',
    position: 'HERO_SLIDER',
    order: 3,
    active: true,
    bg_gradient: 'from-emerald-900/90 via-slate-900/90 to-slate-950/95',
    start_date: '2026-01-01',
    end_date: '2026-12-31',
    created_at: '2026-08-10T08:00:00Z',
  },
  {
    id: 'banner-4',
    title: 'Home Fiber LAN 1Gbps เท่ากันทุกห้อง',
    subtitle: 'นวัตกรรมสายใยแก้วโปร่งแสง ดีไซน์พรีเมียม สปีดเต็มพิกัด 10Gbps Ready',
    description: 'หมดปัญหาเน็ตดรอปในห้องนอน ห้องทำงาน หรือห้องสตรีมเมอร์',
    image: 'https://images.unsplash.com/photo-1600585154340-be6161a56a0c?w=1600&auto=format&fit=crop&q=80',
    badge: '💎 นวัตกรรมระดับไฮเอนด์',
    cta_text: 'แอด LINE ปรึกษาทีมช่าง',
    cta_link: 'https://line.me/ti/p/@aisfibrefanclub',
    link_type: 'LINE',
    position: 'HERO_SLIDER',
    order: 4,
    active: true,
    bg_gradient: 'from-cyan-950/90 via-slate-900/90 to-slate-950/95',
    start_date: '2026-01-01',
    end_date: '2026-12-31',
    created_at: '2026-08-15T08:00:00Z',
  },
  {
    id: 'banner-5',
    title: 'เน็ตคอนโด & หอพัก เริ่มต้นเพียง 269.-/เดือน',
    subtitle: 'ติดตั้งง่าย ไม่เจาะผนัง สัญญาสั้นเพียง 12 เดือน รับเราเตอร์พร้อมใช้งาน',
    description: 'เหมาะสำหรับนิสิต นักศึกษา คนทำงาน หรือผู้เช่าอาศัยในคอนโดมิเนียม',
    image: 'https://images.unsplash.com/photo-1502672260266-1c1ef2d93688?w=1600&auto=format&fit=crop&q=80',
    badge: '🏢 โปรพิเศษชาวคอนโด',
    cta_text: 'ดูแพ็กเกจคอนโด',
    cta_link: '/packages',
    link_type: 'INTERNAL',
    position: 'HOME_MIDDLE',
    order: 5,
    active: true,
    bg_gradient: 'from-indigo-950/90 via-slate-900/90 to-slate-950/95',
    start_date: '2026-01-01',
    end_date: '2026-12-31',
    created_at: '2026-08-20T08:00:00Z',
  },
];

export const PRESET_BANNER_TEMPLATES = [
  {
    name: 'AIS 3BB FIBRE 3 Speed 2Gbps Flagship',
    title: 'AIS 3BB FIBRE 3 สปีด 2Gbps อนาคตที่มากกว่าเน็ตบ้าน',
    subtitle: 'สัมผัสความเร็วแรงสูงสุด พร้อมเราเตอร์ Wi-Fi 7 และกล่อง AIS PLAYBOX ฟรี',
    image: 'https://images.unsplash.com/photo-1544197150-b99a580bb7a8?w=1600&auto=format&fit=crop&q=80',
    badge: '⚡ FLAGSHIP 2026',
    cta_text: 'ดูแพ็กเกจ 2Gbps',
    cta_link: '/packages',
    link_type: 'INTERNAL' as const,
    position: 'HERO_SLIDER' as const,
  },
  {
    name: 'Broadband 24 (1000/500 Mbps 499.-)',
    title: 'Broadband 24 สปีด 1 Gbps เพียง 499.-/เดือน',
    subtitle: 'เน็ตบ้านไฟเบอร์แท้ ยอดนิยมอันดับ 1 ฟรีค่าแรกเข้าและยืมเราเตอร์ WiFi 6',
    image: 'https://images.unsplash.com/photo-1558494949-ef010cbdcc31?w=1600&auto=format&fit=crop&q=80',
    badge: '🔥 ยอดนิยมอันดับ 1',
    cta_text: 'สมัครติดตั้ง 499.-',
    cta_link: '/apply',
    link_type: 'INTERNAL' as const,
    position: 'HERO_SLIDER' as const,
  },
  {
    name: 'Gamer Package 1000/1000 Mbps Low Latency',
    title: 'Gamer Pro สปีด 1000/1000 Mbps ปิงต่ำแยกท่อเกม',
    subtitle: 'VIP Routing เล่นเซิร์ฟนอกไม่แล็ก สตรีมลื่นไหลแบบโปรเพลเยอร์',
    image: 'https://images.unsplash.com/photo-1542751371-adc38448a05e?w=1600&auto=format&fit=crop&q=80',
    badge: '🎮 เพื่อคอเกมตัวจริง',
    cta_text: 'เลือกแพ็กเกจเกมเมอร์',
    cta_link: '/packages',
    link_type: 'INTERNAL' as const,
    position: 'HERO_SLIDER' as const,
  },
  {
    name: 'SuperMESH WiFi 7 Tri-Band',
    title: 'SuperMESH WiFi 7 กระจายสัญญาณรอบบ้าน ไร้จุดอับ',
    subtitle: 'เราเตอร์คู่ความเร็วสูง รองรับการเชื่อมต่อพร้อมกันกว่า 100 เครื่อง',
    image: 'https://images.unsplash.com/photo-1511512578047-dfb367046420?w=1600&auto=format&fit=crop&q=80',
    badge: '🚀 Wi-Fi 7 ล้ำสมัย',
    cta_text: 'เช็คพื้นที่ติดตั้ง',
    cta_link: '/check-area',
    link_type: 'INTERNAL' as const,
    position: 'HERO_SLIDER' as const,
  },
  {
    name: 'Condo Starter Package 269.-',
    title: 'แพ็กเกจคอนโด & หอพัก เริ่มเพียง 269.-/เดือน',
    subtitle: 'สัญญาเริ่ม 12 เดือน ติดตั้งรวดเร็ว ไม่เจาะผนัง พร้อมเราเตอร์',
    image: 'https://images.unsplash.com/photo-1502672260266-1c1ef2d93688?w=1600&auto=format&fit=crop&q=80',
    badge: '🏢 โปรพิเศษคอนโด',
    cta_text: 'สมัครเน็ตคอนโด',
    cta_link: '/apply',
    link_type: 'INTERNAL' as const,
    position: 'HOME_MIDDLE' as const,
  },
  {
    name: 'Entertainment Max + PLAYBOX + Max(HBO)',
    title: 'เน็ตบ้านบันเทิงครบรส ฟรีกล่อง PLAYBOX & Max (HBO)',
    subtitle: 'ชมหนังซีรีส์ระดับโลก VIU และฟุตบอล beIN SPORTS สัญญาณคมชัด 4K',
    image: 'https://images.unsplash.com/photo-1593784991095-a205069470b6?w=1600&auto=format&fit=crop&q=80',
    badge: '📺 ครบทุกความบันเทิง',
    cta_text: 'รับสิทธิ์โปรบันเทิง',
    cta_link: '/packages',
    link_type: 'INTERNAL' as const,
    position: 'HERO_SLIDER' as const,
  },
];

